### ISSUE TITLE
What is the best feedback we can use to send bug reports?

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/hyperRail#130]
Hello,

I plan to add a feedback form in the app when the API return an internal error (usually 502).
Would it be a good idea to add an iRail feedback email address for quick and efficient feedback (subject of the email will of course be filled with the full URL of the call)? If yes => which address?

I often get bad ratings and very poor user feedback and explanations when this bug happens -"doesn't work"- (except this morning, when I received a great and complete info from user)
It is impossible to provide feedback without an automatic form. For instance, when I am on holidays, or not in front of dev computer for a long time makes it quite complicated and might take a few weeks.

I would be pleased to discuss this with iRail team and find the best solution.

Note: sending the user to iRail' Github  bug tracker doesn't seems to be a good idea neither.
Note2: typical impact of a "non automatic feedback" bug: https://goo.gl/3w87YW

Thank all for all your hard work.

**Comment by pietercolpaert** [comment]
Most of the issues that were returned were station issues. I think we need to thoroughly test your stations list and your users will be happier. That's why I've created this issue: https://github.com/iRail/stations/issues/61

Is it ok if I close this issue? We're working on better error logging in the API as well, so that we get automatically informed if something breaks.

**Comment by ChristopheVersieux** [comment]
The list will be updated with API list inside the application (need to find a way to do this without wasting user battery and data plan) in a next release.

Thank a lot for the tests
