### ISSUE TITLE
IP Address blocked from irail.be, api.irail.be

### ISSUE THREAD

**Issue by PolMrt** [iRail/hyperRail#286]
Hi,
I have an app which collects data from your api to create analytics from delay. Since yesterday at 2 pm, it doesn't work anymore. My app calls all the departure from each station every 30min. Have I been blocked?

**Comment by Bertware** [comment]
Hi!

Thanks for getting in touch. The IP address was blocked yesterday, as you were making a huge number of requests which were returning an error 503. At the moment you were blocked, we already received 6000 invalid requests, We expect you to use this status code as a sign to lower the number of requests, as returning that 503 error still uses server resources which we'd like to keep available to other users.

![image](https://user-images.githubusercontent.com/1094793/39092974-1645a430-4618-11e8-8e18-c679779a5990.png)

As you can see from this excerpt, you were polling the same vehicle over and over, multiple times per second.These are only the blocked requests, there were still 3 requests per second passing through. 

Please update your code to do the following:
- Send no more than 3 requests per second
- Don't request the same page twice within 15 seconds, as we're caching it server-side, you won't get any new data. The request will be fulfilled (as long as your not over 3 req/s), but it won't contain new data.

Please change your user agent so we can contact you if should this happen again in the future.  Your user agent is empty now, so we hadn't any lead on who was causing these requests.


If you need to retrieve information on trains, I suggest you do the following strategy:
- Between 3 and 4 am, retrieve every vehicle. Spread your requests over this period of time, this might be possible with even less than 3 requests per seconds.
- Use this information to know when a train will drive, in order to create some sort of index.
- Only retrieve a train starting a half hour before departing, until half an hour after arriving. Poll once a minute while the train is driving, and no more than once every 30 seconds while the train is driving.




https://docs.irail.be/#header-best-practices-when-using-the-api

**Comment by PolMrt** [comment]
Can you help me to configure UserAgent in php please

**Comment by Bertware** [comment]
How you set the user agent in PHP depends on the method you're using to retrieve data. Below I described the method to set your user agent for file_get_contents and cURL, as I suspect you're using one of those methods to download data.

Setting your user-agent using file_get_contents: 
```
$options  = array('http' => array('user_agent' => 'custom user agent string'));
$context  = stream_context_create($options);
$response = file_get_contents('http://domain/path/to/uri', false, $context);
```
source: https://joshtronic.com/2013/06/04/specifying-a-user-agent-when-using-file_get_contents/

Setting your user agent using CURL:
`curl_setopt($curl,CURLOPT_USERAGENT,'your user agent here');`

**Comment by PolMrt** [comment]
Here we are, I all updated! It should be good

**Comment by Bertware** [comment]
Your IP address has been unblocked.
You are still exceeding the request limit, but there is already a significant improvement.
This is a log of all blocked requests in one minute:

```
180.47 - - [22/Apr/2018:13:08:11 +0200] "GET /liveboard/?station=Poulseur&date=220418&time=1125&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.053 cgi:-
180.47 - - [22/Apr/2018:13:08:11 +0200] "GET /liveboard/?station=Sint-Joris-Weert&date=220418&time=1225&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "undefine/0.5 (delay.pol.tf; @)" t:0.050 cgi:-
180.47 - - [22/Apr/2018:13:08:12 +0200] "GET /liveboard/?station=Morlanwelz&date=220418&time=1025&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.051 cgi:-
180.47 - - [22/Apr/2018:13:08:12 +0200] "GET /liveboard/?station=Ruisbroek-Sauvegarde&date=220418&time=1155&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.053 cgi:-
180.47 - - [22/Apr/2018:13:08:12 +0200] "GET /liveboard/?station=Ninove&date=220418&time=1055&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.052 cgi:-
180.47 - - [22/Apr/2018:13:08:26 +0200] "GET /liveboard/?station=Pepinster&date=220418&time=1125&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.053 cgi:-
180.47 - - [22/Apr/2018:13:08:27 +0200] "GET /liveboard/?station=Serskamp&date=220418&time=1225&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "undefine/0.5 (delay.pol.tf; contact@gitewy.net)" t:0.051 cgi:-
180.47 - - [22/Apr/2018:13:08:27 +0200] "GET /liveboard/?station=Michelau&date=220418&time=1025&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.054 cgi:-
180.47 - - [22/Apr/2018:13:08:27 +0200] "GET /liveboard/?station=Rochefort-Jemelle&date=220418&time=1155&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.053 cgi:-
180.47 - - [22/Apr/2018:13:08:28 +0200] "GET /liveboard/?station=Neerpelt&date=220418&time=1055&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.054 cgi:-
180.47 - - [22/Apr/2018:13:08:41 +0200] "GET /liveboard/?station=Muizen&date=220418&time=1055&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.051 cgi:-
180.47 - - [22/Apr/2018:13:08:42 +0200] "GET /liveboard/?station=Oostkamp&date=220418&time=1125&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.053 cgi:-
180.47 - - [22/Apr/2018:13:08:42 +0200] "GET /liveboard/?station=Scheldewindeke&date=220418&time=1225&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "undefine/0.5 (delay.pol.tf; contact@gitewy.net)" t:0.053 cgi:-
180.47 - - [22/Apr/2018:13:08:56 +0200] "GET /liveboard/?station=Pont de Bois&date=220418&time=1155&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.050 cgi:-
180.47 - - [22/Apr/2018:13:08:57 +0200] "GET /liveboard/?station=Moortsele&date=220418&time=1055&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.054 cgi:-
180.47 - - [22/Apr/2018:13:08:58 +0200] "GET /liveboard/?station=Marseille-Saint-Charles&date=220418&time=1025&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.050 cgi:-
180.47 - - [22/Apr/2018:13:08:58 +0200] "GET /liveboard/?station=Marne-la-Vall\xC3\xA9e - Chessy&date=220418&time=1025&arrdep=departure&lang=fr&format=json&fast=false&alerts=false HTTP/1.0" 503 206 "-" "-" t:0.050 cgi:-

```
Note: I redacted your e-mail adress to prevent you getting spam, but it is there, so that's good!

Please fix the following issues:
- Ensure you do not make more than 3 requests per second. The server is a bit flexible (everyone gets a few "burst" requests on top of the limit, so you can exceed it for a few seconds, but this "burst" only gets refilled when you drop below the request limit)
- > Please do lookups based on id! Converting the station name to an ID requires extra processing time on our side. Please convert the names to ids before making your requests. There is a library available here https://github.com/iRail/stations for looking up stations.

- Your user agent is not included in all requests. Ensure that you include it in every request.

As your IP address is now unblocked, it should be easier for you to debug. Thanks for the quick fix!
